# Objective
<ol>
<li>Importing libraries</li>
<li>Importing dataset</li>
<li>Handling Duplicate Values</li>
<li>Handling Missing values</li>
<li>Encoding Categorical data</li>
<li>Feature Scaling</li>
</ol>


In [15]:
# importing libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [16]:
# import dataset
dataset = pd.read_csv('sample_data.csv')
print(dataset)

    Country   Age   Salary Purchased
0    France  44.0  72000.0        No
1     Spain  27.0  48000.0       Yes
2   Germany  30.0  54000.0        No
3     Spain  38.0  61000.0        No
4   Nigeria  18.0  15000.0        No
5   Germany  40.0      NaN       Yes
6    France  35.0  58000.0       Yes
7     Spain   NaN  52000.0        No
8    France  48.0  79000.0       Yes
9   Germany  50.0  83000.0        No
10   France  37.0  67000.0       Yes
11  Nigeria  50.0  60000.0       Yes
12   France  22.0  30000.0        No
13      NaN  44.0  45000.0       Yes
14   France  47.0  78000.0       NaN
15  Nigeria  35.0  43000.0       Yes
16    Spain  34.0  44000.0       Yes
17    Spain  27.0  48000.0       Yes
18    Spain  33.0  48000.0       Yes
19  Nigeria  29.0  77000.0       Yes
20    Spain   NaN  57000.0       Yes
21   France  44.0  48000.0       Yes
22  Germany  50.0  83000.0        No
23   France  37.0  67000.0       Yes
24   France  37.0  23000.0       Yes
25  Germany  45.0  50000.0        No
2

In [18]:
# viewing the first few rows of the dataset
dataset.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Nigeria  18.0  15000.0        No

In [19]:
# viewing statistical info about dataset
dataset.describe()

Age        Salary
count  27.000000     28.000000
mean   36.925926  53642.857143
std     8.757089  19216.532785
min    18.000000  15000.000000
25%    30.000000  44750.000000
50%    37.000000  53000.000000
75%    44.000000  67000.000000
max    50.000000  83000.000000

In [20]:
# dropping duplicate values
dataset = dataset.drop_duplicates()
print(dataset)

    Country   Age   Salary Purchased
0    France  44.0  72000.0        No
1     Spain  27.0  48000.0       Yes
2   Germany  30.0  54000.0        No
3     Spain  38.0  61000.0        No
4   Nigeria  18.0  15000.0        No
5   Germany  40.0      NaN       Yes
6    France  35.0  58000.0       Yes
7     Spain   NaN  52000.0        No
8    France  48.0  79000.0       Yes
9   Germany  50.0  83000.0        No
10   France  37.0  67000.0       Yes
11  Nigeria  50.0  60000.0       Yes
12   France  22.0  30000.0        No
13      NaN  44.0  45000.0       Yes
14   France  47.0  78000.0       NaN
15  Nigeria  35.0  43000.0       Yes
16    Spain  34.0  44000.0       Yes
18    Spain  33.0  48000.0       Yes
19  Nigeria  29.0  77000.0       Yes
20    Spain   NaN  57000.0       Yes
21   France  44.0  48000.0       Yes
24   France  37.0  23000.0       Yes
25  Germany  45.0  50000.0        No
27  Nigeria  30.0  30000.0       Yes
28  Nigeria  29.0  15000.0        No


In [21]:
#We can run the .describe() method on our dataset to check if there are any changes

dataset.describe()

Age        Salary
count  23.000000     24.000000
mean   36.782609  51541.666667
std     8.852101  19352.517344
min    18.000000  15000.000000
25%    30.000000  43750.000000
50%    37.000000  51000.000000
75%    44.000000  62500.000000
max    50.000000  83000.000000

## Handling Missing Data
In our dataset, there may be some missing values. We cannot train our model with a dataset that contains missing values. So we have to check if our dataset has missing values.

In [22]:
# checking for missing values
dataset.isnull()

Country    Age  Salary  Purchased
0     False  False   False      False
1     False  False   False      False
2     False  False   False      False
3     False  False   False      False
4     False  False   False      False
5     False  False    True      False
6     False  False   False      False
7     False   True   False      False
8     False  False   False      False
9     False  False   False      False
10    False  False   False      False
11    False  False   False      False
12    False  False   False      False
13     True  False   False      False
14    False  False   False       True
15    False  False   False      False
16    False  False   False      False
18    False  False   False      False
19    False  False   False      False
20    False   True   False      False
21    False  False   False      False
24    False  False   False      False
25    False  False   False      False
27    False  False   False      False
28    False  False   False      False

In [23]:
# checking the number of missing data
dataset.isnull().sum()

Country      1
Age          2
Salary       1
Purchased    1
dtype: int64

We can handle missing values by:

Deleting the row/column: This is one of the easiest ways to handle missing values. If we have a lot of missing values in a column, we can just remove that column from our dataset. We could also delete any row with missing values. The only problem with this method is that we lose some information needed by our model to make accurate predictions.

Replacing missing values with Mean/Mode/Median: For numerical data, we can replace missing values with the mean, mode, or median of the column with the missing value. This way we get to preserve some information needed by our model. The mean is mostly preferred.

Replacing with values close to the missing value: We could also replace missing values with the value that comes before or after it in the same column.

For the columns ‘Country’ and ‘Purchased’, I will remove the rows with missing values.

In [24]:
# Dropping categorical data rows with missing values
dataset.dropna(how='any', subset=['Country', 'Purchased'], inplace=True)

Before I replace the missing values in the other columns, I will separate the independent variables and target variable. The target variable is what we are trying to predict. While the independent variables are the features that will help us make the predictions. The columns ‘Country’, ‘Age’, and ‘Salary’ are our independent variables, while ‘Purchased’ is our target variable.

In the code above, for the parameter ‘how’, the argument ‘any’ drops the row if any value is null. But the argument ‘all’ will only drop the row if all the values are null. The argument for the ‘subset’ parameter is a list containing the columns we want to remove missing values from. ‘inplace=True’ modifies our original dataframe, instead of returning a copy of the dataframe.

In [25]:
# Splitting dataset into independent & dependent variable
X = dataset[['Country', 'Age', 'Salary']].values
y = dataset['Purchased'].values
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Nigeria' 18.0 15000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]
 ['Nigeria' 50.0 60000.0]
 ['France' 22.0 30000.0]
 ['Nigeria' 35.0 43000.0]
 ['Spain' 34.0 44000.0]
 ['Spain' 33.0 48000.0]
 ['Nigeria' 29.0 77000.0]
 ['Spain' nan 57000.0]
 ['France' 44.0 48000.0]
 ['France' 37.0 23000.0]
 ['Germany' 45.0 50000.0]
 ['Nigeria' 30.0 30000.0]
 ['Nigeria' 29.0 15000.0]]


In [26]:
print(y)

['No' 'Yes' 'No' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes' 'Yes' 'No'
 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'No' 'Yes' 'No']


We will replace the missing values in the ‘Age’ and ‘Salary’ columns with the mean.

In [27]:
# replacing the missing values in the age & salary column with the mean
# import the SimpleImputer class from the sklearn library
from sklearn.impute import SimpleImputer
print(X[:, 1:3])

[[44.0 72000.0]
 [27.0 48000.0]
 [30.0 54000.0]
 [38.0 61000.0]
 [18.0 15000.0]
 [40.0 nan]
 [35.0 58000.0]
 [nan 52000.0]
 [48.0 79000.0]
 [50.0 83000.0]
 [37.0 67000.0]
 [50.0 60000.0]
 [22.0 30000.0]
 [35.0 43000.0]
 [34.0 44000.0]
 [33.0 48000.0]
 [29.0 77000.0]
 [nan 57000.0]
 [44.0 48000.0]
 [37.0 23000.0]
 [45.0 50000.0]
 [30.0 30000.0]
 [29.0 15000.0]]


In [28]:
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])
print(X[:, 1:3])

[[44.0 72000.0]
 [27.0 48000.0]
 [30.0 54000.0]
 [38.0 61000.0]
 [18.0 15000.0]
 [40.0 50636.36363636364]
 [35.0 58000.0]
 [35.95238095238095 52000.0]
 [48.0 79000.0]
 [50.0 83000.0]
 [37.0 67000.0]
 [50.0 60000.0]
 [22.0 30000.0]
 [35.0 43000.0]
 [34.0 44000.0]
 [33.0 48000.0]
 [29.0 77000.0]
 [35.95238095238095 57000.0]
 [44.0 48000.0]
 [37.0 23000.0]
 [45.0 50000.0]
 [30.0 30000.0]
 [29.0 15000.0]]


In the SimpleImputer() class, np.nan represents the missing values in our NumPy array. That will be the argument to the ‘missing_values’ parameter. ‘strategy=mean’ means we will be replacing the missing values with the mean.

The .fit() method will connect our ‘imputer’ object to the matrix of features X. But to do the replacement, we need to call another method, this is the .transform() method. This will apply the transformation, thereby replacing the missing values with the mean.

Encoding Categorical Data
Deborah Rumsey defines categorical data as the type of data that is used to group information with similar characteristics. In our dataset, the ‘Country’ & ‘Purchased’ columns contain categorical data.

Our Machine Learning Model works with numbers, so our model won’t understand these categorical data. We need to encode these categorical data into numbers. To do this, we apply One-Hot Encoding. 

From sklearn.compose, we will import the ColumnTransformer class. We will also import OneHotEncoder class from the preprocessing module of the sklearn library.

In [29]:
# Handling Categorical Data
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('enconder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[1.0 0.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 0.0 30.0 54000.0]
 [0.0 0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 0.0 18.0 15000.0]
 [0.0 1.0 0.0 0.0 40.0 50636.36363636364]
 [1.0 0.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 0.0 1.0 35.95238095238095 52000.0]
 [1.0 0.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 0.0 37.0 67000.0]
 [0.0 0.0 1.0 0.0 50.0 60000.0]
 [1.0 0.0 0.0 0.0 22.0 30000.0]
 [0.0 0.0 1.0 0.0 35.0 43000.0]
 [0.0 0.0 0.0 1.0 34.0 44000.0]
 [0.0 0.0 0.0 1.0 33.0 48000.0]
 [0.0 0.0 1.0 0.0 29.0 77000.0]
 [0.0 0.0 0.0 1.0 35.95238095238095 57000.0]
 [1.0 0.0 0.0 0.0 44.0 48000.0]
 [1.0 0.0 0.0 0.0 37.0 23000.0]
 [0.0 1.0 0.0 0.0 45.0 50000.0]
 [0.0 0.0 1.0 0.0 30.0 30000.0]
 [0.0 0.0 1.0 0.0 29.0 15000.0]]


In the ColumnTransformer class, for the argument ‘transformers’, we have a list containing a tuple as the parameter. The first item ‘encoder’ is the type of transformation we want. ‘OneHotEncoder()’ is the class that will handle the transformation. ‘[0]’ is the index of the column we want to encode. If we have multiple columns to transform, we can put them in the list. In this case, we only have one column with index 0, so it is only 0 that is in the list. The remainder=’passthrough’ means we want to leave the other columns the way they are without transforming them.

In [30]:
print(y)

['No' 'Yes' 'No' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes' 'Yes' 'No'
 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'No' 'Yes' 'No']


In [31]:
# Encoding the target variable
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
print(y)

[0 1 0 0 0 1 1 0 1 0 1 1 0 1 1 1 1 1 1 1 0 1 0]


### Splitting the Dataset

Splitting our dataset into training & test set is another important step in data preprocessing. We will use part of the dataset to train the model. The other part of the dataset will be used to evaluate our model, to see how it performs on new data that it hasn’t seen before. We will do the split in the 80:20 ratio. 80% of the dataset will be used for training, while 20% will be used for testing.

In [32]:
# Splitting Dataset into Training and Test Set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2                                                , random_state=2)

For the train_test_split function, the argument X is our features (independent variable). The argument y is our target variable,
‘test_size=0.2’ means 20% of the dataset will be used as the test set. The random_state sets a seed to the random generator.

In [33]:
print(X_train)

[[0.0 0.0 1.0 0.0 29.0 77000.0]
 [0.0 0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 0.0 0.0 22.0 30000.0]
 [0.0 1.0 0.0 0.0 50.0 83000.0]
 [0.0 0.0 1.0 0.0 18.0 15000.0]
 [1.0 0.0 0.0 0.0 37.0 67000.0]
 [0.0 1.0 0.0 0.0 40.0 50636.36363636364]
 [0.0 0.0 0.0 1.0 35.95238095238095 57000.0]
 [0.0 0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 0.0 30.0 54000.0]
 [0.0 0.0 0.0 1.0 35.95238095238095 52000.0]
 [1.0 0.0 0.0 0.0 37.0 23000.0]
 [1.0 0.0 0.0 0.0 44.0 48000.0]
 [0.0 0.0 1.0 0.0 50.0 60000.0]
 [0.0 0.0 1.0 0.0 29.0 15000.0]
 [0.0 0.0 1.0 0.0 35.0 43000.0]
 [0.0 0.0 0.0 1.0 33.0 48000.0]
 [1.0 0.0 0.0 0.0 48.0 79000.0]]


In [34]:
print(X_test)

[[0.0 1.0 0.0 0.0 45.0 50000.0]
 [1.0 0.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 0.0 30.0 30000.0]
 [1.0 0.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 0.0 1.0 34.0 44000.0]]


In [35]:
print(y_train)

[1 0 0 0 0 1 1 1 1 0 0 1 1 1 0 1 1 1]


In [36]:
print(y_test)

[0 0 1 1 1]


### Feature Scaling
This is the final step of data preprocessing. Feature scaling puts all our data in the same range and on the same scale. We do not want any feature of our dataset to dominate another feature. We don’t have to apply feature scaling to all datasets, especially if the features of that dataset are already within the same range. We could apply normalization or standardization to our dataset. The formula is shown below:

$x = \frac{x - mean(x)}{standard Deviation(x)}$; $x = \frac{x - min(x)}{max(x) - min(x)}$

Standardization puts all the values between the range of -3 and 3. But normalization will always give you positive values between the range of 0 and 1.
We will apply standardization. We will use the StandardScaler class from the preprocessing module of the sklearn library. We won’t apply feature scaling to the one-hot encoded columns (dummy variables). We don’t want to change the interpretation of those values.

In [37]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 4:] = sc.fit_transform(X_train[:, 4:])

The .fit() method of the StandardScaler() class will just calculate the mean and standard deviation for X_train, while the .transform() method will transform the values with the formula above. We can do the fit and transform in one line of code by using the .fit_transform() method.

In [38]:
print(X_train)

[[0.0 0.0 1.0 0.0 -0.746521345589145 1.351588046193331]
 [0.0 0.0 0.0 1.0 0.28796566772827725 0.5327257531467691]
 [1.0 0.0 0.0 0.0 -1.55112235594714 -1.0538199396309444]
 [0.0 1.0 0.0 0.0 1.6672816854848402 1.6586614060857916]
 [0.0 0.0 1.0 0.0 -2.0108943618659945 -1.8215033393620963]
 [1.0 0.0 0.0 0.0 0.1730226662485637 0.8397991130392297]
 [0.0 1.0 0.0 0.0 0.5178516706877044 0.0023263133325189464]
 [0.0 0.0 0.0 1.0 0.05260618850791099 0.3280101798851286]
 [0.0 0.0 0.0 1.0 -0.9764073485485721 -0.13259985995356244]
 [0.0 1.0 0.0 0.0 -0.6315783441094314 0.17447349993889827]
 [0.0 0.0 0.0 1.0 0.05260618850791099 0.07211571330807803]
 [1.0 0.0 0.0 0.0 0.1730226662485637 -1.4120721928388154]
 [1.0 0.0 0.0 0.0 0.9776236766065588 -0.13259985995356244]
 [0.0 0.0 1.0 0.0 1.6672816854848402 0.481546859831359]
 [0.0 0.0 1.0 0.0 -0.746521345589145 -1.8215033393620963]
 [0.0 0.0 1.0 0.0 -0.056863336710863466 -0.388494326530613]
 [0.0 0.0 0.0 1.0 -0.28674933967029065 -0.13259985995356244]
 [1.0 0.

In [39]:
print(X_test)

[[0.0 1.0 0.0 0.0 45.0 50000.0]
 [1.0 0.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 0.0 30.0 30000.0]
 [1.0 0.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 0.0 1.0 34.0 44000.0]]


In [41]:
X_test[:, 4:] = sc.transform(X_test[:, 4:])
print(X_test)

[[0.0 1.0 0.0 0.0 1.0925666780862724 -0.030242073322742206]
 [1.0 0.0 0.0 0.0 0.9776236766065588 1.0956935796162803]
 [0.0 0.0 1.0 0.0 -0.6315783441094314 -1.0538199396309444]
 [1.0 0.0 0.0 0.0 -0.056863336710863466 0.37918907320053874]
 [0.0 0.0 0.0 1.0 -0.17180633819057706 -0.3373154332152029]]


### Conclusion
Before we can train a Machine Learning model, we need to clean our data.
If we don’t clean our dataset, we will run into some problems during training. We need to handle missing values, encode categorical variables, and sometimes apply feature scaling to our dataset.